# Numpy Practice

In [2]:
import numpy as np

In [7]:
print(np.__version__)

2.3.5


In [3]:
a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
c = np.zeros(4)
print(c)

[0. 0. 0. 0.]


In [6]:
d=np.ones(4)
print(d)

[1. 1. 1. 1.]


In [7]:
e=np.arange(0,10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
f = np.array([[1,2,3,4], [5,6,7,8]])
print(f)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [14]:
arr.shape

(1, 1, 1, 1, 4)

In [15]:
arr.size

4

In [19]:
arr = np.array([1,2,3,4])
print(arr[2])
print(arr[1:3])

3
[2 3]


# Mathematical Operations

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [21]:
print(a*b)

[ 4 10 18]


In [24]:
print(sum(a))
print(sum(b))

6
15


In [25]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [26]:
np.random.rand(5)

array([0.77403949, 0.58888542, 0.49859465, 0.70915771, 0.70742258])

In [27]:
np.random.randint(1,10,5)

array([1, 9, 1, 7, 4], dtype=int32)

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a= [1,2,3.5,"hello"] #List with diff data types
a_arr = np.array(a)  #conver list to array
a_arr

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [5]:
# try multi dimentional list
l = [[1,2,3] , [4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
# Now convert list into array it will look like matrix
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
arr=np.linspace(0,1)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [20]:
arr = np.linspace(0,10,100)
arr

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [24]:
arr = np.random.rand(10) # from 0 to 1
arr

array([0.994487  , 0.8479449 , 0.29584254, 0.87384791, 0.35821129,
       0.98737185, 0.01063023, 0.55503301, 0.81579056, 0.97625441])

In [25]:
np.random.randn(10)   # from -3 to 3

array([ 0.29579734,  0.83352786,  0.28494026,  1.34543995,  0.63471422,
        0.52078243,  0.06634139, -1.42590186,  1.03051319,  1.27561328])

In [30]:
np.random.randint(10,20,5) # 5 random numbers between 10 to 20

array([18, 19, 12, 16, 18], dtype=int32)

# Array Methods

In [31]:
arr

array([0.994487  , 0.8479449 , 0.29584254, 0.87384791, 0.35821129,
       0.98737185, 0.01063023, 0.55503301, 0.81579056, 0.97625441])

In [32]:
arr.min()

np.float64(0.010630231719990668)

In [34]:
arr = np.array([[1,3,5],[7,8,9],[2,4,6]])

In [35]:
arr

array([[1, 3, 5],
       [7, 8, 9],
       [2, 4, 6]])

In [36]:
arr.min()

np.int64(1)

In [37]:
arr.max()

np.int64(9)

In [38]:
arr.sum()

np.int64(45)

In [39]:
arr.shape

(3, 3)

In [40]:
arr.size

9

In [42]:
np.sum(arr,axis=0) # sum column wise

array([10, 15, 20])

In [43]:
np.sum(arr,axis=1) # sum row wise

array([ 9, 24, 12])

# Reshaping and Resizing

In [44]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [47]:
arr.reshape((5,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

# Indexing and Slicing of Vectors

In [48]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
arr[3]

np.int64(14)

In [50]:
arr[-1]

np.int64(20)

In [51]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [53]:
arr[:5]

array([11, 12, 13, 14, 15])

In [54]:
arr[4:8]

array([15, 16, 17, 18])

In [55]:
arr[::2]

array([11, 13, 15, 17, 19])

In [56]:
arr[2:11:2]

array([13, 15, 17, 19])

# Indexing and Slicing of Matrix

In [58]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [59]:
arr[0]

array([1, 2, 3, 4, 5])

In [60]:
arr[3]

array([16, 17, 18, 19, 20])

In [61]:
arr[0,0]

np.int64(1)

In [63]:
arr[1,4]

np.int64(10)

In [64]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [68]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [70]:
arr[2:4,2:5]

array([[13, 14, 15],
       [18, 19, 20]])

In [71]:
arr[1:5,2:4]

array([[ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [72]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# Boolean Indexing

In [73]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [74]:
bool_index = arr % 2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [75]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Arithmatic Operations

In [76]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [77]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [78]:
a1-a2

array([-5, -5, -5, -5, -5])

In [79]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [80]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [81]:
a1//a2

array([0, 0, 0, 0, 0])

In [82]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [83]:
l = [10,20,30,40]
arr = np.array(l)

In [84]:
arr+10

array([20, 30, 40, 50])

# Deep and Shallow Copy

In [86]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [91]:
a # Shallow copy means no changes in main array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [93]:
b = a
b[0] = 99 # Deep coppy means change in main array as well
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [94]:
# to avaoid deep copy use copy()
b= a.copy()
b[1] = 100
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [95]:
b

array([ 99, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

# Matrix Operations

In [96]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [97]:
A

array([[1, 2],
       [3, 4]])

In [98]:
B

array([[5, 6],
       [7, 8]])

In [101]:
#Multiplication of matrix method 1
A @ B 

array([[19, 22],
       [43, 50]])

In [102]:
#Multiplication of matrix method 2
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [104]:
# Exchange rows and columns
A.T

array([[1, 3],
       [2, 4]])

# Stacking Array

In [105]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting Array

In [109]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [112]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [113]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [114]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

# Exersize

Valid Sudoku

In [115]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [117]:
r_sum = np.sum(s, axis=1)
r_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [118]:
c_sum = np.sum(s, axis=0)
c_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [119]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [122]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [171]:
# column : [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [140]:
# Find shape of the matrix
data.shape

(5, 3)

In [141]:
# Find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [142]:
# Extract Math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [143]:
# Find highest Science mark
data[:,2].max() #Method 1
np.max(data[:,2]) # Method 2

np.int64(95)

In [144]:
# Get details of the studen who scored more than 90 in maths
bool_index = data[:,1] >= 90
data1 = data[bool_index]
data1

array([[19, 92, 88],
       [20, 90, 85]])

In [156]:
# Increase math marks of all students by 5
data[:,1] += 5
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [160]:
# Find how many students are younger than 19
data1 = data[:,0] < 19
len(data[data1])

3

In [162]:
# Calculate the average markes in each subject
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [168]:
# Get data of students who scored at least 80 in both subject
data[(data[:,1] >=80) & (data[:,2] >= 80)]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [172]:
#  Replace all Science marks < 75 with 0
data[:,2][data[:,2]< 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])