# Numpy Practice

In [2]:
import numpy as np

In [7]:
print(np.__version__)

2.3.5


In [3]:
a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
c = np.zeros(4)
print(c)

[0. 0. 0. 0.]


In [6]:
d=np.ones(4)
print(d)

[1. 1. 1. 1.]


In [7]:
e=np.arange(0,10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
f = np.array([[1,2,3,4], [5,6,7,8]])
print(f)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [14]:
arr.shape

(1, 1, 1, 1, 4)

In [15]:
arr.size

4

In [19]:
arr = np.array([1,2,3,4])
print(arr[2])
print(arr[1:3])

3
[2 3]


# Mathematical Operations

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [21]:
print(a*b)

[ 4 10 18]


In [24]:
print(sum(a))
print(sum(b))

6
15


In [25]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [26]:
np.random.rand(5)

array([0.77403949, 0.58888542, 0.49859465, 0.70915771, 0.70742258])

In [27]:
np.random.randint(1,10,5)

array([1, 9, 1, 7, 4], dtype=int32)